function [U,FxPred] = wingCtrlFunc(gammaw,CL0, CL1, CD0, CD1, CD2, F, rho, vapp, Aref)
 U=[inf inf];
 FxPred=[inf inf];
U(1)=(-1/2).*CD2.^(-1).*(CD1+2.*CD2.*gammaw+(-1).*CL1.*tan(gammaw)+ ...
  Aref.^(-1).*rho.^(-1).*vapp.^(-2).*abs(cos(gammaw)).*sec(gammaw).* ...
  ((-1).*Aref.*rho.*vapp.^2.*(8.*CD2.*F.*sec(gammaw)+(-1).*Aref.* ...
  rho.*vapp.^2.*(CD1.^2+(-4).*CD0.*CD2+4.*CD2.*CL0.*tan(gammaw)+(-2) ...
  .*CD1.*CL1.*tan(gammaw)+CL1.^2.*tan(gammaw).^2))).^(1/2));
U(2) = (1/2).*CD2.^(-1).*((-1).*CD1+(-2).*CD2.*gammaw+CL1.*tan(gammaw)+ ...
  Aref.^(-1).*rho.^(-1).*vapp.^(-2).*abs(cos(gammaw)).*sec(gammaw).* ...
  ((-1).*Aref.*rho.*vapp.^2.*(8.*CD2.*F.*sec(gammaw)+(-1).*Aref.* ...
  rho.*vapp.^2.*(CD1.^2+(-4).*CD0.*CD2+4.*CD2.*CL0.*tan(gammaw)+(-2) ...
  .*CD1.*CL1.*tan(gammaw)+CL1.^2.*tan(gammaw).^2))).^(1/2));
FxPred(1)=(1/2).*Aref.*rho.*vapp.^2.*(sin(gammaw).*(CL0+CL1.*(gammaw+(-1/2) ...
  .*CD2.^(-1).*(CD1+2.*CD2.*gammaw+(-1).*CL1.*tan(gammaw))))+(-1).* ...
  cos(gammaw).*(CD0+CD1.*(gammaw+(-1/2).*CD2.^(-1).*(CD1+2.*CD2.* ...
  gammaw+(-1).*CL1.*tan(gammaw)))+CD2.*(gammaw+(-1/2).*CD2.^(-1).*( ...
  CD1+2.*CD2.*gammaw+(-1).*CL1.*tan(gammaw))).^2));
FxPred(2)=(1/2).*Aref.*rho.*vapp.^2.*(sin(gammaw).*(CL0+CL1.*(gammaw+(-1/2) ...
  .*CD2.^(-1).*(CD1+2.*CD2.*gammaw+(-1).*CL1.*tan(gammaw)+Aref.^(-1) ...
  .*rho.^(-1).*vapp.^(-2).*abs(cos(gammaw)).*sec(gammaw).*((-1).* ...
  Aref.*rho.*vapp.^2.*(8.*CD2.*F.*sec(gammaw)+(-1).*Aref.*rho.* ...
  vapp.^2.*(CD1.^2+(-4).*CD0.*CD2+4.*CD2.*CL0.*tan(gammaw)+(-2).* ...
  CD1.*CL1.*tan(gammaw)+CL1.^2.*tan(gammaw).^2))).^(1/2))))+(-1).* ...
  cos(gammaw).*(CD0+CD1.*(gammaw+(-1/2).*CD2.^(-1).*(CD1+2.*CD2.* ...
  gammaw+(-1).*CL1.*tan(gammaw)+Aref.^(-1).*rho.^(-1).*vapp.^(-2).* ...
  abs(cos(gammaw)).*sec(gammaw).*((-1).*Aref.*rho.*vapp.^2.*(8.* ...
  CD2.*F.*sec(gammaw)+(-1).*Aref.*rho.*vapp.^2.*(CD1.^2+(-4).*CD0.* ...
  CD2+4.*CD2.*CL0.*tan(gammaw)+(-2).*CD1.*CL1.*tan(gammaw)+CL1.^2.* ...
  tan(gammaw).^2))).^(1/2)))+CD2.*(gammaw+(-1/2).*CD2.^(-1).*(CD1+ ...
  2.*CD2.*gammaw+(-1).*CL1.*tan(gammaw)+Aref.^(-1).*rho.^(-1).* ...
  vapp.^(-2).*abs(cos(gammaw)).*sec(gammaw).*((-1).*Aref.*rho.* ...
  vapp.^2.*(8.*CD2.*F.*sec(gammaw)+(-1).*Aref.*rho.*vapp.^2.*( ...
  CD1.^2+(-4).*CD0.*CD2+4.*CD2.*CL0.*tan(gammaw)+(-2).*CD1.*CL1.* ...
  tan(gammaw)+CL1.^2.*tan(gammaw).^2))).^(1/2))).^2));
end